doctrine_migrations:
  migrations_paths:
    # namespace is arbitrary but should be different from App\Presentation\Console\Migrations
    # as migrations classes should NOT be autoloaded
    'App\Presentation\Console\Migration': '%kernel.project_dir%/src/Presentation/Console/Migration'
  enable_profiler: false
