monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
        channels: ["!event"]
      # uncomment to get logging in your browser
      # you may have to allow bigger header sizes in your Web server configuration
      #firephp:
      #    type: firephp
      #    level: info
      #chromephp:
      #    type: chromephp
      #    level: info
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        channels: ["!event"]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug

when@prod:
  monolog:
    handlers:
      app:
        type: fingers_crossed
        action_level: error
        handler: app_nested
        excluded_http_codes: [404, 405]
        channels: ["!event"]
      app_nested:
        type: rotating_file
        path: '%kernel.logs_dir%/error.log'
        level: error
        max_files: 10
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine"]
      telegram_wrapped:
        type: fingers_crossed
        action_level: error
        handler: telegram
        excluded_http_codes: [404, 405]
        channels: ["!event", "!messenger.log"]
      telegram:
        type: service
        id: monolog.custom_handlers.telegram.error
        level: error
        channels: ["!event", "!messenger.log"]
