nelmio_api_doc:
  documentation:
    openapi: 3.1.0
    info:
      title: Secret Service
      description: Service to send secret messages
      version: 1.0.0
    tags:
      - name: health
        description: Ручки для проверки работоспособности сервера
    servers:
      - url: '%env(APP_HOST)%'
      - url: http://secret.loc
        description: Local development server
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
