version: "3.9"
services:
  postgresql:
    image: postgres:17
    container_name: postgresql-container
    hostname: postgresql
    restart: always
    ports:
      - "${PG_EXTERNAL_PORT}:5432"
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DBNAME}"
    networks:
      - caddy
  php:
    build:
      context: ./
      dockerfile: docker/php/dev/Dockerfile
    container_name: php-container
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: phpsocket
        target: /var/run
    networks:
      - caddy
  nginx:
    image: nginx
    container_name: nginx-container
    volumes:
      - type: bind
        source: ./docker/nginx/dev.nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: .
        target: /app
      - type: volume
        source: phpsocket
        target: /var/run
        volume:
          nocopy: true
    depends_on:
      - php
    networks:
      - caddy
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  phpsocket:
networks:
  caddy:
    external: true
